/**
 * Cron presets mirroring @nestjs/schedule's CronExpression enum, exposed in the
 * frontend recurrence selector. `value` is the literal cron expression; the
 * sentinel `CRON_CUSTOM` means "user types their own expression".
 *
 * NOTE: the API evaluator ticks once per minute, so sub-minute presets
 * (every second / N seconds) cannot fire more often than once a minute in
 * practice — they are listed for completeness/parity with @nestjs/schedule.
 */
export const CRON_CUSTOM = 'custom' as const;

export const CRON_PRESETS = [
  { label: 'Every second', value: '* * * * * *' },
  { label: 'Every 5 seconds', value: '*/5 * * * * *' },
  { label: 'Every 10 seconds', value: '*/10 * * * * *' },
  { label: 'Every 30 seconds', value: '*/30 * * * * *' },
  { label: 'Every minute', value: '*/1 * * * *' },
  { label: 'Every 5 minutes', value: '0 */5 * * * *' },
  { label: 'Every 10 minutes', value: '0 */10 * * * *' },
  { label: 'Every 30 minutes', value: '0 */30 * * * *' },
  { label: 'Every hour', value: '0 0-23/1 * * *' },
  { label: 'Every 2 hours', value: '0 0-23/2 * * *' },
  { label: 'Every 3 hours', value: '0 0-23/3 * * *' },
  { label: 'Every 4 hours', value: '0 0-23/4 * * *' },
  { label: 'Every 5 hours', value: '0 0-23/5 * * *' },
  { label: 'Every 6 hours', value: '0 0-23/6 * * *' },
  { label: 'Every 7 hours', value: '0 0-23/7 * * *' },
  { label: 'Every 8 hours', value: '0 0-23/8 * * *' },
  { label: 'Every 9 hours', value: '0 0-23/9 * * *' },
  { label: 'Every 10 hours', value: '0 0-23/10 * * *' },
  { label: 'Every 11 hours', value: '0 0-23/11 * * *' },
  { label: 'Every 12 hours', value: '0 0-23/12 * * *' },
  { label: 'Every day at 1 AM', value: '0 01 * * *' },
  { label: 'Every day at 2 AM', value: '0 02 * * *' },
  { label: 'Every day at 3 AM', value: '0 03 * * *' },
  { label: 'Every day at 4 AM', value: '0 04 * * *' },
  { label: 'Every day at 5 AM', value: '0 05 * * *' },
  { label: 'Every day at 6 AM', value: '0 06 * * *' },
  { label: 'Every day at 7 AM', value: '0 07 * * *' },
  { label: 'Every day at 8 AM', value: '0 08 * * *' },
  { label: 'Every day at 9 AM', value: '0 09 * * *' },
  { label: 'Every day at 10 AM', value: '0 10 * * *' },
  { label: 'Every day at 11 AM', value: '0 11 * * *' },
  { label: 'Every day at noon', value: '0 12 * * *' },
  { label: 'Every day at 1 PM', value: '0 13 * * *' },
  { label: 'Every day at 2 PM', value: '0 14 * * *' },
  { label: 'Every day at 3 PM', value: '0 15 * * *' },
  { label: 'Every day at 4 PM', value: '0 16 * * *' },
  { label: 'Every day at 5 PM', value: '0 17 * * *' },
  { label: 'Every day at 6 PM', value: '0 18 * * *' },
  { label: 'Every day at 7 PM', value: '0 19 * * *' },
  { label: 'Every day at 8 PM', value: '0 20 * * *' },
  { label: 'Every day at 9 PM', value: '0 21 * * *' },
  { label: 'Every day at 10 PM', value: '0 22 * * *' },
  { label: 'Every day at 11 PM', value: '0 23 * * *' },
  { label: 'Every day at midnight', value: '0 0 * * *' },
  { label: 'Every week (Sunday)', value: '0 0 * * 0' },
  { label: 'Every weekday (Mon-Fri)', value: '0 0 * * 1-5' },
  { label: 'Every weekend (Sat & Sun)', value: '0 0 * * 6,0' },
  { label: '1st of month at midnight', value: '0 0 1 * *' },
  { label: '1st of month at noon', value: '0 12 1 * *' },
  { label: 'Every 2nd hour', value: '0 */2 * * *' },
  { label: 'Every 2nd hour (1 AM-11 PM)', value: '0 1-23/2 * * *' },
  { label: 'Every 2 months', value: '0 0 1 */2 *' },
  { label: 'Every quarter', value: '0 0 1 */3 *' },
  { label: 'Every 6 months', value: '0 0 1 */6 *' },
  { label: 'Every year', value: '0 0 1 1 *' },
  { label: 'Every 30 min (9 AM-5 PM)', value: '0 */30 9-17 * * *' },
  { label: 'Every 30 min (9 AM-6 PM)', value: '0 */30 9-18 * * *' },
  { label: 'Every 30 min (10 AM-7 PM)', value: '0 */30 10-19 * * *' },
  { label: 'Mon-Fri at 1 AM', value: '0 0 01 * * 1-5' },
  { label: 'Mon-Fri at 2 AM', value: '0 0 02 * * 1-5' },
  { label: 'Mon-Fri at 3 AM', value: '0 0 03 * * 1-5' },
  { label: 'Mon-Fri at 4 AM', value: '0 0 04 * * 1-5' },
  { label: 'Mon-Fri at 5 AM', value: '0 0 05 * * 1-5' },
  { label: 'Mon-Fri at 6 AM', value: '0 0 06 * * 1-5' },
  { label: 'Mon-Fri at 7 AM', value: '0 0 07 * * 1-5' },
  { label: 'Mon-Fri at 8 AM', value: '0 0 08 * * 1-5' },
  { label: 'Mon-Fri at 9 AM', value: '0 0 09 * * 1-5' },
  { label: 'Mon-Fri at 9:30 AM', value: '0 30 09 * * 1-5' },
  { label: 'Mon-Fri at 10 AM', value: '0 0 10 * * 1-5' },
  { label: 'Mon-Fri at 11 AM', value: '0 0 11 * * 1-5' },
  { label: 'Mon-Fri at 11:30 AM', value: '0 30 11 * * 1-5' },
  { label: 'Mon-Fri at 12 PM', value: '0 0 12 * * 1-5' },
  { label: 'Mon-Fri at 1 PM', value: '0 0 13 * * 1-5' },
  { label: 'Mon-Fri at 2 PM', value: '0 0 14 * * 1-5' },
  { label: 'Mon-Fri at 3 PM', value: '0 0 15 * * 1-5' },
  { label: 'Mon-Fri at 4 PM', value: '0 0 16 * * 1-5' },
  { label: 'Mon-Fri at 5 PM', value: '0 0 17 * * 1-5' },
  { label: 'Mon-Fri at 6 PM', value: '0 0 18 * * 1-5' },
  { label: 'Mon-Fri at 7 PM', value: '0 0 19 * * 1-5' },
  { label: 'Mon-Fri at 8 PM', value: '0 0 20 * * 1-5' },
  { label: 'Mon-Fri at 9 PM', value: '0 0 21 * * 1-5' },
  { label: 'Mon-Fri at 10 PM', value: '0 0 22 * * 1-5' },
  { label: 'Mon-Fri at 11 PM', value: '0 0 23 * * 1-5' },
] as const;

export type CronPreset = (typeof CRON_PRESETS)[number];
