export const PATHS = {
  STATUS: {
    GET: '/status',
  },
  BATCH: {
    LIST: '/batch',
    GET: '/batch/:id',
    LIST_JOBS: '/batch/:id/jobs',
    LIST_PRODUCTS: '/batch/:id/products',
    LIST_INPUTS: '/batch/:id/inputs',
    LIST_LOGS: '/batch/:id/logs',
    CREATE: '/batch',
    REPLAY: '/batch/:id/replay',
    UPDATE_PRIORITY: '/batch/:id/priority',
  },
  JOB: {
    LIST: '/job',
    GET: '/job/:id',
    CANCEL: '/job/:id/cancel',
    PAUSE: '/job/:id/pause',
    RESUME: '/job/:id/resume',
  },
  PRODUCTION_CHAIN: {
    LIST: '/production-chain',
    GET: '/production-chain/:id',
    CREATE: '/production-chain',
    UPDATE: '/production-chain/:id',
    DELETE: '/production-chain/:id',
    ADD_EDGE: '/production-chain/:id/edges',
    UPDATE_EDGE: '/production-chain/:id/edges/:edgeId',
    DELETE_EDGE: '/production-chain/:id/edges/:edgeId',
    ADD_PROCESSING_CHAIN: '/production-chain/:id/processing-chains',
    UPDATE_PROCESSING_CHAIN: '/production-chain/:id/processing-chains/:pcId',
    DELETE_PROCESSING_CHAIN: '/production-chain/:id/processing-chains/:pcId',
    LINK_PRODUCT_TYPE: '/production-chain/:id/product-types/:productTypeId',
    UNLINK_PRODUCT_TYPE: '/production-chain/:id/product-types/:productTypeId',
    LIST_COMPATIBLE_PRODUCTS: '/production-chain/:id/compatible-products',
    IMPORT: '/production-chain/import',
    IMPORT_PREVIEW: '/production-chain/import/preview',
    ADD_NODE: '/production-chain/:id/versions/:versionId/nodes',
    UPDATE_NODE: '/production-chain/:id/versions/:versionId/nodes/:nodeId',
    DELETE_NODE: '/production-chain/:id/versions/:versionId/nodes/:nodeId',
  },
  PROCESSING_SCRIPT: {
    LIST: '/processing-script',
    GET: '/processing-script/:id',
  },
  DATASET: {
    LIST: '/dataset',
    GET: '/dataset/:id',
    CREATE: '/dataset',
    UPDATE: '/dataset/:id',
    DELETE: '/dataset/:id',
  },
  DATA_CENTER: {
    LIST: '/data-center',
    GET: '/data-center/:id',
  },
  HOST: {
    LIST: '/host',
    GET: '/host/:id',
    REGISTER: '/host/register',
    HEARTBEAT: '/host/:id/heartbeat',
    UPDATE_STATUS: '/host/:id/status',
    INGEST_LOGS: '/host/:id/logs',
    LIST_LOGS: '/host/:id/logs',
    CAPACITY_SUMMARY: '/host/capacity-summary',
    STATUS_LIST: '/host/status',
    ACTIVE: '/host/active',
    METRICS: '/host/:id/metrics',
    LIST_BATCHES: '/host/:id/batches',
  },
  AUTH: {
    LOGIN: '/auth/login',
    CALLBACK: '/auth/callback',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
  },
  USER: {
    LIST: '/user',
    ME_SETTINGS: '/user/me/settings',
  },
  PROJECT: {
    LIST: '/project',
    GET: '/project/:id',
    CREATE: '/project',
    UPDATE: '/project/:id',
    DELETE: '/project/:id',
    SET_DEFAULT: '/project/:id/set-default',
  },
  PRODUCT_TYPE: {
    LIST: '/product-type',
    GET: '/product-type/:id',
    CREATE: '/product-type',
    UPDATE: '/product-type/:id',
    DELETE: '/product-type/:id',
  },
  PRODUCT: {
    LIST: '/product',
    GET: '/product/:id',
    CREATE: '/product',
    UPDATE: '/product/:id',
    DELETE: '/product/:id',
  },
  POOL: {
    LIST: '/pool',
    GET: '/pool/:id',
    CREATE: '/pool',
    UPDATE: '/pool/:id',
    DELETE: '/pool/:id',
    ADD_HOST: '/pool/:id/hosts/:hostId',
    REMOVE_HOST: '/pool/:id/hosts/:hostId',
  },
  AUXILIARY_CONFIGURATION: {
    LIST: '/auxiliary-configuration',
    GET: '/auxiliary-configuration/:id',
    CREATE: '/auxiliary-configuration',
    UPDATE: '/auxiliary-configuration/:id',
    DELETE: '/auxiliary-configuration/:id',
  },
  PROCESSOR_VERSION: {
    LIST: '/processor-version',
    GET: '/processor-version/:id',
    CREATE: '/processor-version',
    UPDATE: '/processor-version/:id',
    DELETE: '/processor-version/:id',
  },
  TASK: {
    LIST: '/task',
    GET: '/task/:id',
    CREATE: '/task',
    UPDATE: '/task/:id',
    DELETE: '/task/:id',
    TRIGGER: '/task/:id/trigger',
    EXPAND: '/task/:id/expand',
    UPDATE_PRIORITY: '/task/:id/priority',
    EXECUTION_TREE: '/task/:id/execution-tree',
    BATCHES: '/task/:id/batches',
    HISTORY: '/task/:id/history',
    STATUS_SUMMARY: '/task/status-summary',
  },
  TASK_SCHEDULE: {
    LIST: '/task-schedule',
    GET: '/task-schedule/:id',
    CREATE: '/task-schedule',
    UPDATE: '/task-schedule/:id',
    DELETE: '/task-schedule/:id',
  },
  HEALTH: {
    LIVE: '/healthz',
    READY: '/readyz',
    METRICS: '/metrics',
  },
  PRODUCTION_MODE_RULE: {
    LIST: '/production-mode-rule',
    GET: '/production-mode-rule/:id',
    CREATE: '/production-mode-rule',
    UPDATE: '/production-mode-rule/:id',
    DELETE: '/production-mode-rule/:id',
  },
  PROCESSING_CHAIN_TEMPLATE: {
    LIST: '/processing-chain-template',
    GET: '/processing-chain-template/:id',
    CREATE: '/processing-chain-template',
    UPDATE: '/processing-chain-template/:id',
    DELETE: '/processing-chain-template/:id',
  },
  PRODUCT_INGESTION_HOOK: {
    LIST: '/product-ingestion-hook',
    GET: '/product-ingestion-hook/:id',
    CREATE: '/product-ingestion-hook',
    UPDATE: '/product-ingestion-hook/:id',
    DELETE: '/product-ingestion-hook/:id',
  },
  WORKER: {
    NEXT_JOB: '/worker/:id/next-job',
    JOB_RESULT: '/worker/:id/jobs/:jobId/result',
    JOB_OUTPUTS: '/worker/:id/jobs/:jobId/outputs',
    BATCH_INPUTS: '/worker/batches/:batchId/inputs',
  },
  SCHEDULER: {
    STATUS: '/scheduler/status',
    HEARTBEAT: '/scheduler/heartbeat',
    EXPAND_TASK: '/scheduler/task/:id/expand',
  },
  METRICS: {
    CO2: '/metrics/co2',
  },
  AUDIT_LOG: {
    LIST: '/audit-log',
  },
  TASK_TABLE: {
    IMPORT: '/task-table/import',
    COMMIT: '/task-table/import/:planId/commit',
  },
  ODATA: {
    LIST: '/odata/:resource',
    GET: '/odata/:resource/:id',
    CREATE: '/odata/:resource',
    UPDATE: '/odata/:resource/:id',
    DELETE: '/odata/:resource/:id',
  },
};
